### PR TITLE
Mate engine

### PR DESCRIPTION
**Pull request by kazu-nanoha**
YANEURAOU_EDITION = MATE_ENGINE の時のエラー修正

### CODE REVIEW

**Comment by yaneurao** [comment]
ありがとうございます(｀･ω･´)ｂ

**Comment by yaneurao** [comment]
//time_ms = std::max(time_ms, 1LL);	// これだと Cygwin clang v 3.9.1 でエラーになる…
      time_ms = time_ms > 1LL ? time_ms : 1LL;

この部分のコードなのですが、windows.hがmax()をマクロで定義しているためではないかと思うのですが、前者のコードを

     time_ms = (std::max)(time_ms, 1LL)

のように括弧で括ってもCygwinのclangではコンパイルが通らないでしょうか？

**Comment by kazu-nanoha** [comment]
やねさん、おはようございます。

今試してみると、cygwinではclang++/g++どちらも同じエラーになるようです。
なお、第2引数の1LLを1Lに変更すると通りました。

★clang++ 3.9.1
engine/mate-engine/mate-search.cpp:490:16: error: no matching function for
call
      to 'max'
        time_ms = (std::max)(time_ms, 1LL);     // これだと Cygwin clan...
                  ^~~~~~~~~~
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/algorithmfwd.h:357:5:
note:
      candidate template ignored: deduced conflicting types for parameter
'_Tp'
      ('long' vs. 'long long')
    max(const _Tp&, const _Tp&);
    ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3463:5:
note:
      candidate template ignored: could not match
      'initializer_list<type-parameter-0-0>' against 'long'
    max(initializer_list<_Tp> __l, _Compare __comp)
    ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/algorithmfwd.h:362:5:
note:
      candidate function template not viable: requires 3 arguments, but 2
were
      provided
    max(const _Tp&, const _Tp&, _Compare);
    ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3457:5:
note:
      candidate function template not viable: requires single argument
'__l',
      but 2 arguments were provided
    max(initializer_list<_Tp> __l)
    ^

★g++ 5.4.0
engine/mate-engine/mate-search.cpp: 関数 ‘void MateEngine::dfpn(Position&)’ 内:
engine/mate-engine/mate-search.cpp:490:39: エラー: ‘max(long int&, long long
int)’ の呼び出しに適合する関数がありません
      time_ms = (std::max)(time_ms, 1LL); // これだと Cygwin clang v 3.9.1
でエラーになる…
                                       ^
In file included from
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/algorithm:61:0,
                 from engine/mate-engine/../../extra/config.h:444,
                 from engine/mate-engine/../../shogi.h:51,
                 from engine/mate-engine/mate-search.cpp:1:
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algobase.h:219:5:
備考: candidate: template<class _Tp> constexpr const _Tp& std::max(const
_Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algobase.h:219:5:
備考:   template argument deduction/substitution failed:
engine/mate-engine/mate-search.cpp:490:39: 備考:   deduced conflicting types
for parameter ‘const _Tp’ (‘long int’ and ‘long long int’)
      time_ms = (std::max)(time_ms, 1LL); // これだと Cygwin clang v 3.9.1
でエラーになる…
                                       ^
In file included from
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/algorithm:61:0,
                 from engine/mate-engine/../../extra/config.h:444,
                 from engine/mate-engine/../../shogi.h:51,
                 from engine/mate-engine/mate-search.cpp:1:
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algobase.h:265:5:
備考: candidate: template<class _Tp, class _Compare> constexpr const _Tp&
std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algobase.h:265:5:
備考:   template argument deduction/substitution failed:
engine/mate-engine/mate-search.cpp:490:39: 備考:   deduced conflicting types
for parameter ‘const _Tp’ (‘long int’ and ‘long long int’)
      time_ms = (std::max)(time_ms, 1LL); // これだと Cygwin clang v 3.9.1
でエラーになる…
                                       ^
In file included from
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/algorithm:62:0,
                 from engine/mate-engine/../../extra/config.h:444,
                 from engine/mate-engine/../../shogi.h:51,
                 from engine/mate-engine/mate-search.cpp:1:
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3457:5: 備考:
candidate: template<class _Tp> constexpr _Tp
std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3457:5:
備考:   template argument deduction/substitution failed:
engine/mate-engine/mate-search.cpp:490:39: 備考:   mismatched types
‘std::initializer_list<_Tp>’ and ‘long int’
      time_ms = (std::max)(time_ms, 1LL); // これだと Cygwin clang v 3.9.1
でエラーになる…
                                       ^
In file included from
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/algorithm:62:0,
                 from engine/mate-engine/../../extra/config.h:444,
                 from engine/mate-engine/../../shogi.h:51,
                 from engine/mate-engine/mate-search.cpp:1:
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3463:5: 備考:
candidate: template<class _Tp, class _Compare> constexpr _Tp
std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/lib/gcc/x86_64-pc-cygwin/5.4.0/include/c++/bits/stl_algo.h:3463:5:
備考:   template argument deduction/substitution failed:
engine/mate-engine/mate-search.cpp:490:39: 備考:   mismatched types
‘std::initializer_list<_Tp>’ and ‘long int’
      time_ms = (std::max)(time_ms, 1LL); // これだと Cygwin clang v 3.9.1
でエラーになる…
                                       ^
make[1]: *** [Makefile:158: ../obj/engine/mate-engine/mate-search.o] エラー 1

2017年12月1日 6:34 yaneurao <notifications@github.com>:

**Comment by yaneurao** [comment]
あー、意味がわかりました。

std::chrono::millisecondsが、C++の規格上、45bit以上の符号付き整数型となっていて、VC++ではlong long、clangなどではlongになっているので、これをautoで受けてしまうとそのあと1LLと型が異なるのでエラーになるんでしょうね。autoではなくlong longで受けるか、1LLではなくdecltype(time_ms)(1) とするかですかね。後者でどうですかね。

      time_ms = std::max(time_ms, decltype(time_ms)(1));

**Comment by kazu-nanoha** [comment]
はい、それでお願いします。こちらで何か作業必要でしょうか？

2017/12/01 9:18 "yaneurao" <notifications@github.com>:

あー、意味がわかりました。

std::chrono::millisecondsが、C++の規格上、45bit以上の符号付き整数型となっていて、VC++ではlong
long、clangなどではlongになっているので、これをautoで受けてしまうとそのあと1LLと型が異なるのでエラーになるんでしょうね。autoではなくlong
longで受けるか、1LLではなくdecltype(time_ms)(1) とするかですかね。後者でどうですかね。

  time_ms = std::max(time_ms, decltype(time_ms)(1));

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yaneurao/YaneuraOu/pull/70#issuecomment-348363465>, or mute
the thread

**Comment by yaneurao** [comment]
私のほうで修正してcommitしておきました(｀･ω･´)ｂ
これでコンパイルが通らなかったりしたらまた教えてください。
https://github.com/yaneurao/YaneuraOu/commit/e728ef91821bbecb153cd6855b715f5a7d36e1da

**Pull request merged**
